/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { actualizarProducto, crearProducto, eliminarProducto, listarProductos } from "../api/productos";
import ProductoForm from "../components/ProductoForm";

const porPagina = 10;
function AdminProductos() {
    const [productos, setProductos] = useState([]), [busqueda, setBusqueda] = useState(""), [pagina, setPagina] = useState(1), [cargando, setCargando] = useState(true), [error, setError] = useState(""), [modal, setModal] = useState(null), [guardando, setGuardando] = useState(false);
    async function cargar() { setCargando(true); setError(""); try { const data = await listarProductos(); setProductos(data.data); } catch { setError("No se pudieron cargar los productos."); } finally { setCargando(false); } }
    useEffect(function () { cargar(); }, []);
    const filtrados = useMemo(function () { return productos.filter(function (p) { return p.nombre.toLowerCase().includes(busqueda.toLowerCase()); }); }, [productos, busqueda]);
    const totalPaginas = Math.max(1, Math.ceil(filtrados.length / porPagina)); const visibles = filtrados.slice((pagina - 1) * porPagina, pagina * porPagina);
    async function guardar(datos) { setGuardando(true); setError(""); try { if (modal) await actualizarProducto(modal.id, datos); else await crearProducto(datos); setModal(null); await cargar(); } catch (e) { setError(e.response?.data?.mensaje || "No se pudo guardar el producto."); } finally { setGuardando(false); } }
    async function borrar(producto) { if (!window.confirm("¿Eliminar “" + producto.nombre + "”?")) return; try { await eliminarProducto(producto.id); await cargar(); } catch (e) { setError(e.response?.data?.mensaje || "No se pudo eliminar el producto."); } }
    return <section><Cabecera etiqueta="Productos" titulo="Catálogo de productos" /><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-between"><input value={busqueda} onChange={function(e){setBusqueda(e.target.value);setPagina(1);}} placeholder="Buscar por nombre" className="border border-line bg-ticket px-3 py-2 font-mono-ticket text-sm outline-none focus:border-forest" /><button onClick={function(){setModal({});}} className="flex cursor-pointer items-center justify-center gap-2 bg-forest px-4 py-2 font-mono-ticket text-sm text-paper"><Plus size={17}/>Nuevo producto</button></div>{error && <Alerta texto={error}/>} {cargando ? <Carga/> : <div className="mt-5 overflow-x-auto border border-line bg-ticket"><table className="w-full min-w-175 text-left"><thead className="border-b border-line bg-paper font-mono-ticket text-xs uppercase text-ink/60"><tr><th className="p-3">Nombre</th><th>Precio</th><th>Disponible</th><th>Categoría</th><th className="p-3">Acciones</th></tr></thead><tbody>{visibles.map(function(p){return <tr key={p.id} className="border-b border-line last:border-0"><td className="p-3 font-medium">{p.nombre}</td><td>${Number(p.precio).toFixed(2)}</td><td>{p.stock-(p.stockReservado||0)}</td><td>{p.categoria}</td><td className="p-3"><div className="flex gap-2"><button onClick={function(){setModal(p);}} className="cursor-pointer text-forest" aria-label="Editar"><Pencil size={17}/></button><button onClick={function(){borrar(p);}} className="cursor-pointer text-red-600" aria-label="Eliminar"><Trash2 size={17}/></button></div></td></tr>;})}</tbody></table>{!visibles.length&&<p className="p-5 font-mono-ticket text-sm text-ink/60">No hay productos que coincidan.</p>}</div>}<Paginacion pagina={pagina} total={totalPaginas} cambiar={setPagina}/>{modal!==null&&<ProductoForm producto={modal.id?modal:null} alCerrar={function(){setModal(null);}} alGuardar={guardar} guardando={guardando}/>}</section>;
}
export function Cabecera({etiqueta,titulo}){return <><p className="font-mono-ticket text-xs uppercase tracking-[.25em] text-forest">{etiqueta}</p><h1 className="mt-2 font-display text-3xl sm:text-4xl">{titulo}</h1></>;}
export function Carga(){return <p className="mt-8 font-mono-ticket text-sm text-ink/60">Cargando...</p>;} export function Alerta({texto}){return <p className="mt-4 border border-red-200 bg-red-50 p-3 font-mono-ticket text-sm text-red-700">{texto}</p>;} export function Paginacion({pagina,total,cambiar}){return total>1&&<div className="mt-6 flex justify-center gap-4 font-mono-ticket text-sm"><button disabled={pagina===1} onClick={function(){cambiar(pagina-1);}} className="cursor-pointer text-forest disabled:opacity-30">Anterior</button><span>{pagina} / {total}</span><button disabled={pagina===total} onClick={function(){cambiar(pagina+1);}} className="cursor-pointer text-forest disabled:opacity-30">Siguiente</button></div>;}
export default AdminProductos;
