import { useState } from "react";
import { X } from "lucide-react";

function AjustarStockModal({ producto, alCerrar, alGuardar, guardando }) {
    const [cantidad, setCantidad] = useState(""); const [motivo, setMotivo] = useState(""); const [error, setError] = useState("");
    function enviar(e) { e.preventDefault(); const ajuste = Number(cantidad); if (!Number.isInteger(ajuste) || ajuste === 0 || !motivo.trim()) return setError("Indicá un ajuste entero distinto de cero y su motivo."); if (ajuste < 0 && producto.stockDisponible + ajuste < 0) return setError("El ajuste no puede dejar el stock disponible en negativo."); alGuardar({ tipo: ajuste > 0 ? "ENTRADA" : "SALIDA", cantidad: Math.abs(ajuste), referenciaId: motivo.trim() }); }
    return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/45 p-4" role="dialog" aria-modal="true"><form onSubmit={enviar} className="w-full max-w-md bg-ticket p-6 shadow-xl"><div className="flex justify-between"><div><p className="font-mono-ticket text-xs uppercase tracking-wide text-forest">Stock</p><h2 className="font-display text-2xl">Ajustar {producto.nombre}</h2></div><button type="button" onClick={alCerrar} className="cursor-pointer p-1" aria-label="Cerrar"><X /></button></div><p className="mt-3 font-mono-ticket text-sm text-ink/60">Disponible actual: {producto.stockDisponible}</p><label className="mt-4 block font-mono-ticket text-xs uppercase tracking-wide text-ink/60">Cantidad (+/-)<input type="number" step="1" required value={cantidad} onChange={function(e){setCantidad(e.target.value);}} className="mt-1 w-full border border-line bg-paper p-2 text-ink outline-none focus:border-forest" /></label><label className="mt-4 block font-mono-ticket text-xs uppercase tracking-wide text-ink/60">Motivo<textarea required value={motivo} onChange={function(e){setMotivo(e.target.value);}} className="mt-1 min-h-20 w-full border border-line bg-paper p-2 text-ink outline-none focus:border-forest" /></label>{error && <p className="mt-3 font-mono-ticket text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={alCerrar} className="cursor-pointer px-4 py-2 font-mono-ticket text-sm">Cancelar</button><button disabled={guardando} className="cursor-pointer bg-forest px-4 py-2 font-mono-ticket text-sm text-paper disabled:opacity-60">{guardando ? "Guardando..." : "Confirmar"}</button></div></form></div>;
}
export default AjustarStockModal;
